engines: 
  eslint:
    enabled: true
    channel: "eslint-2"
    checks:
      complexity:
        enabled: true
      import/no-unresolved:
        enabled: false
  duplication:
      enabled: true
      config:
        languages:
        - javascript
          #mass_threshold: 30
  fixme:
    enabled: true
ratings:
  paths:
  - src/**/*.js
exclude_paths:
- test
- gulpfile.js
