language: node_js
node_js: 6
branches:
    only:
        - master
        - dev
efore_script:
    - npm install -g gulp
script:
    - gulp build
after_success:
    - npm run coveralls
deploy:
    provider: npm
    on:
        tags: true
        branch: master
    skip_cleanup: true
    email: ket4yiit@gmail.com
    api_key:
        secure: "LQb67GVNB8poe4+n7DsOx6j2VeflOFcJ1UL+cxj/9lpC3oByEsg/o/p9d4sJ5+uyFGKiV9XGfxLU6rJCjm6PWaYNY7DhloY5dcdG8/I6fMg4CmS3qPGGaPKLwoSEcrFHvDLIJ7ZRWYEqDUlP6G1x8CJN2E77Xu0kVYVkHpfLJRu5y+J/qiLQRzTvEmXCL1zfhCJd8zuYWvtu9aiKtggrnTnE9tcK1BTsXiU9k208IJFF+Z9ji0WkOc9h5bH0TYI/yQ+MNRajqmBSN9+GS1I0cLktd6mGOsmFaj1ypmTSJAPJA/HtByZkLFd7KR9KWfjTsBjuWToHXprQKlXG7TJtC5ROsGPKbLEx+W2xfynCXdZj9iWmrRmd0E2xLW8QmxbNHQ8sg1duhV+o7brtBwq4wtJRlMrHq4r4iC4fbWukCyP+GE6iCXvbUsRPwVZD6xFB4RiaahnN9vU5xjKIbt3wEIA990ON1A7UfsOgYunH6BFIDq6QIeHVg5KQpZbTMDUC6OdjgVVmx1TrN3wPd9KyE3FjiHOPbZReuC7v0hVouaHAiCEIvA5BnDNuZEwL5zBd4qNwY55H0IIg3Cr3tsf6haO5MC9pgXpNX6H4ThxvpduiojlCCeW31Xrw5KP+b7rqPGpbvJ0VzhalOJWPVi14CAmhrpgJNBWU1KepTzRrJvI="
addons:
  code_climate:
    repo_token:
      secure: "fOyIfTIJY7DDtHlEg6j+KRVYbDrFHNKRgPFDPFD8ZBKkZowCeQecJF3ZNvHeBBiJMcNOODjn358LxH69P7NreAKAzsuvdGGqMaRjKQTwniwBjE6qPQrMgcvEwVuSUcUZi7LMgWkF2Py8GD7fojrJKqomn7ZSbsu2mGZXJUy0AeWdNTgakYDkt8+UFn+oyXrdg9KN7axbfqkR0IQMOSoBCIM+eq+nirwLrLR6ICvekPy0g9gO3FgY2hAognz+6zg184mIwGOBroT+wsvU+h/cfeRVOYP4kQXIYNhby+2oxlp7/m8fzA1JVt3U3NJJaMMO7IUEOfq1NghNhFWS221WO5UyaK4nLGRFYnllJnsGwcxNoUFmesUfMLDKgYnD3KeFGGGr8sk2X95G+JFPKTrXqZ5CJjC/DlptBv90E2yQ5V9HUgLACRNelUWxvNZ8UJ+cy7A0nS97GrBcDI8FOJJ25nRkFwfXaQR72gCtVrL6XfuEM9BzHGD9KEN9BAsK1Ye8OIFVM8G60BPFgQaqZVoeJjfn8hpUr4rdSKX6d7V1i2oJtJSr6eqoCmjh9QL6UZavDiFTX833K9VBZPm0tayl8EyArA6mFHhQWYsazg2zx1gL0OGGXOuJKsvqr2/UlIxlJZ4o8L2tBPxawN8/8haYkmziDSiNvCzKIN/oc1ITUfk="

